---
# Source: kyverno/templates/hooks/post-delete-configmap.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-remove-configmap
  namespace: kyverno
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.4.4
    helm.sh/chart: kyverno-3.4.4
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "0"
---
# Source: kyverno/templates/hooks/post-delete-configmap.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno:remove-configmap
  namespace: kyverno
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.4.4
    helm.sh/chart: kyverno-3.4.4
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "0"
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - list
    - get
    - delete
---
# Source: kyverno/templates/hooks/post-delete-configmap.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kyverno:remove-configmap
  namespace: kyverno
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.4.4
    helm.sh/chart: kyverno-3.4.4
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno:remove-configmap
subjects:
  - kind: ServiceAccount
    name: kyverno-remove-configmap
    namespace: kyverno
---
# Source: kyverno/templates/hooks/post-delete-configmap.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kyverno-remove-configmap
  namespace: kyverno
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.4.4
    helm.sh/chart: kyverno-3.4.4
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "10"
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: kyverno-remove-configmap
      restartPolicy: Never
      containers:
        - name: kubectl
          image: "bitnami/kubectl:1.32.3"
          imagePullPolicy: 
          command:
            - /bin/bash
            - '-c'
            - |-
              set -euo pipefail
              kubectl delete cm --ignore-not-found -n kyverno kyverno
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
