---
# Source: kyverno/templates/hooks/post-upgrade-migrate-resources.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-migrate-resources
  namespace: kyverno
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.4.4
    helm.sh/chart: kyverno-3.4.4
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "100"
---
# Source: kyverno/templates/hooks/post-upgrade-migrate-resources.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:migrate-resources
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.4.4
    helm.sh/chart: kyverno-3.4.4
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "100"
rules:
  - apiGroups:
    - kyverno.io
    resources:
    - '*'
    verbs:
    - get
    - list
    - update
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions/status
    verbs:
    - update
---
# Source: kyverno/templates/hooks/post-upgrade-migrate-resources.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kyverno:migrate-resources
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.4.4
    helm.sh/chart: kyverno-3.4.4
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "100"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:migrate-resources
subjects:
  - kind: ServiceAccount
    name: kyverno-migrate-resources
    namespace: kyverno
---
# Source: kyverno/templates/hooks/post-upgrade-migrate-resources.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kyverno-migrate-resources
  namespace: kyverno
  labels:
    app.kubernetes.io/component: hooks
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 3.4.4
    helm.sh/chart: kyverno-3.4.4
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "200"
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: kyverno-migrate-resources
      restartPolicy: Never
      containers:
        - name: kubectl
          image: "reg.kyverno.io/kyverno/kyverno-cli:v1.14.4"
          imagePullPolicy: IfNotPresent
          args:
            - migrate
            - --resource
            - cleanuppolicies.kyverno.io
            - --resource
            - clustercleanuppolicies.kyverno.io
            - --resource
            - clusterpolicies.kyverno.io
            - --resource
            - globalcontextentries.kyverno.io
            - --resource
            - policies.kyverno.io
            - --resource
            - policyexceptions.kyverno.io
            - --resource
            - updaterequests.kyverno.io
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
